export const FETCH_OPENSTACK_PROJECTS_FULFILLED = 'FETCH_OPENSTACK_PROJECTS_FULFILLED';
export const FETCH_OPENSTACK_PROJECTS_REJECTED = 'FETCH_OPENSTACK_PROJECTS_REJECTED';

export const FETCH_OPENSTACK_PROJECT_BY_ID_FULFILLED = 'FETCH_OPENSTACK_PROJECT_BY_ID_FULFILLED';
export const FETCH_OPENSTACK_PROJECT_BY_ID_REJECTED = 'FETCH_OPENSTACK_PROJECT_BY_ID_REJECTED';

export const FETCH_FLAVOR_FULFILLED = 'FETCH_FLAVOR_FULFILLED';
export const FETCH_FLAVOR_REJECTED = 'FETCH_FLAVOR_REJECTED';

export const FETCH_SERVER_FULFILLED = 'FETCH_SERVER_FULFILLED';
export const FETCH_SERVER_REJECTED = 'FETCH_SERVER_REJECTED';

export const FETCH_SERVER_BY_ID_FULFILLED = 'FETCH_SERVER_BY_ID_FULFILLED';
export const FETCH_SERVER_BY_ID_REJECTED = 'FETCH_SERVER_BY_ID_REJECTED';

export const FETCH_NETRON_FULFILLED = 'FETCH_NETRON_FULFILLED';
export const FETCH_NETRON_REJECTED = 'FETCH_NETRON_REJECTED';

export const FETCH_IMAGES_FULFILLED = 'FETCH_IMAGES_FULFILLED';
export const FETCH_IMAGES_REJECTED = 'FETCH_IMAGES_REJECTED';

export const FETCH_TEMPLATES_FULFILLED = 'FETCH_TEMPLATES_FULFILLED';
export const FETCH_TEMPLATES_REJECTED = 'FETCH_TEMPLATES_REJECTED';

export const FETCH_TEMPLATE_BY_ID_FULFILLED = 'FETCH_TEMPLATE_BY_ID_FULFILLED';
export const FETCH_TEMPLATE_BY_ID_REJECTED = 'FETCH_TEMPLATE_BY_ID_REJECTED';

export const FETCH_RECOURCES_FULFILLED = 'FETCH_RECOURCES_FULFILLED';
export const FETCH_RECOURCES_REJECTED = 'FETCH_RECOURCES_REJECTED';
