export const TRAIN_NEURAL_NETWROK_FULFILLED = 'TRAIN_NEURAL_NETWROK_FULFILLED';
export const TRAIN_NEURAL_NETWROK_REJECTED = 'TRAIN_NEURAL_NETWROK_REJECTED';

export const TEST_NEURAL_NETWROK_FULFILLED = 'TEST_NEURAL_NETWROK_FULFILLED';
export const TEST_NEURAL_NETWROK_REJECTED = 'TEST_NEURAL_NETWROK_REJECTED';

export const SAVE_DESCRIPTION_FULFILLED = 'SAVE_DESCRIPTION_FULFILLED';
export const SAVE_DESCRIPTION_REJECTED = 'SAVE_DESCRIPTION_REJECTED';

export const FETCH_DESCRIPTIONS_FULFILLED = 'FETCH_DESCRIPTIONS_FULFILLED';
export const FETCH_DESCRIPTIONS_REJECTED = 'FETCH_DESCRIPTIONS_REJECTED';

export const FETCH_SAVED_DESCRIPTIONS_FULFILLED = 'FETCH_SAVED_DESCRIPTIONS_FULFILLED';
export const FETCH_SAVED_DESCRIPTIONS_REJECTED = 'FETCH_SAVED_DESCRIPTIONS_REJECTED';

export const FETCH_DESCRIPTION_BY_ID_FULFILLED = 'FETCH_DESCRIPTION_BY_ID_FULFILLED';
export const FETCH_DESCRIPTION_BY_ID_REJECTED = 'FETCH_DESCRIPTION_BY_ID_REJECTED';

export const FETCH_MODELS_BY_DESC_ID_FULFILLED = 'FETCH_MODELS_BY_DESC_ID_FULFILLED';
export const FETCH_MODELS_BY_DESC_ID_REJECTED = 'FETCH_MODELS_BY_DESC_ID_REJECTED';

export const FETCH_MODELS_LOGS_FULFILLED = 'FETCH_MODELS_LOGS_FULFILLED';
export const FETCH_MODELS_LOGS_REJECTED = 'FETCH_MODELS_LOGS_REJECTED';

export const FETCH_MODEL_BY_ID_FULFILLED = 'FETCH_MODEL_BY_ID_FULFILLED';
export const FETCH_MODEL_BY_ID_REJECTED = 'FETCH_MODEL_BY_ID_REJECTED';

export const RUN_INSTANCE_DESCRIPTION_FULFILLED = 'RUN_INSTANCE_DESCRIPTION_FULFILLED';
export const RUN_INSTANCE_DESCRIPTION_REJECTED = 'RUN_INSTANCE_DESCRIPTION_REJECTED';

export const GENERATE_VINNSL_FULFILLED = 'GENERATE_VINNSL_FULFILLED';
export const GENERATE_VINNSL_REJECTED = 'GENERATE_VINNSL_REJECTED';


export const CREATE_VINNSL_DESCRIPTION_FULFILLED = 'CREATE_VINNSL_DESCRIPTION_FULFILLED';
export const CREATE_VINNSL_DESCRIPTION_REJECTED = 'CREATE_VINNSL_DESCRIPTION_REJECTED';


export const CREATE_PROJECT_FULFILLED = 'CREATE_PROJECT_FULFILLED';
export const CREATE_PROJECT_REJECTED = 'CREATE_PROJECT_REJECTED';


export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED';
export const FETCH_PROJECTS_REJECTED = 'FETCH_PROJECTS_REJECTED';

export const ADD_NN_ID_TO_PROJECT_FULFILLED = 'ADD_NN_ID_TO_PROJECT_FULFILLED';
export const ADD_NN_ID_TO_PROJECT_REJECTED = 'ADD_NN_ID_TO_PROJECT_REJECTED';

export const DELETE_PROJECT_FULFILLED = 'DELETE_PROJECT_FULFILLED';
export const DELETE_PROJECT_REJECTED = 'DELETE_PROJECT_REJECTED';
